/**
 * QuickScan Studio - Action Registry
 * Phase 18: Single Source of Truth for all 28 Supported Smart Actions & Confirmation Governance
 */
import { ActionDefinition, ActionId } from './types';

export const ACTION_REGISTRY: Record<ActionId, ActionDefinition> = {
  COPY_TEXT: {
    id: 'COPY_TEXT',
    label: 'Copy Text',
    subtitle: 'Copy raw payload string to device clipboard',
    icon: 'copy',
    category: 'QUICK',
    accessibilityHint: 'Copies the decoded QR or barcode string to your system clipboard.',
  },
  SHARE_CONTENT: {
    id: 'SHARE_CONTENT',
    label: 'Share Code',
    subtitle: 'Share decoded payload via system dialog',
    icon: 'share',
    category: 'QUICK',
    accessibilityHint: 'Opens the system share sheet to send decoded data to apps or friends.',
  },
  OPEN_WEBSITE: {
    id: 'OPEN_WEBSITE',
    label: 'Open in Web Browser',
    subtitle: 'Launch default browser to view website',
    icon: 'url',
    category: 'PRIMARY',
    isPrimary: true,
    accessibilityHint: 'Opens the web URL in your default internet browser.',
  },
  CALL_PHONE: {
    id: 'CALL_PHONE',
    label: 'Call Phone Number',
    subtitle: 'Open native dialer with telephone number',
    icon: 'phone',
    category: 'PRIMARY',
    isPrimary: true,
    accessibilityHint: 'Opens your phone dialer with this telephone number ready to call.',
  },
  SEND_SMS: {
    id: 'SEND_SMS',
    label: 'Send SMS Message',
    subtitle: 'Open messaging app with pre-filled recipient and text',
    icon: 'sms',
    category: 'PRIMARY',
    isPrimary: true,
    accessibilityHint: 'Opens SMS texting application to send a message to this recipient.',
  },
  COMPOSE_EMAIL: {
    id: 'COMPOSE_EMAIL',
    label: 'Compose New Email',
    subtitle: 'Launch mail client with pre-populated parameters',
    icon: 'email',
    category: 'PRIMARY',
    isPrimary: true,
    accessibilityHint: 'Opens default email app with recipient and subject line filled out.',
  },
  OPEN_MAPS: {
    id: 'OPEN_MAPS',
    label: 'Open in Maps',
    subtitle: 'View geographic coordinates on maps navigation',
    icon: 'location',
    category: 'PRIMARY',
    isPrimary: true,
    accessibilityHint: 'Launches GPS mapping software to navigate to these coordinates.',
  },
  OPEN_GOOGLE_MAPS: {
    id: 'OPEN_GOOGLE_MAPS',
    label: 'Open in Google Maps',
    subtitle: 'Launch Google Maps navigation engine',
    icon: 'location',
    category: 'PRIMARY',
    isPrimary: true,
    accessibilityHint: 'Opens location in Google Maps app or web application.',
  },
  OPEN_PLAY_STORE: {
    id: 'OPEN_PLAY_STORE',
    label: 'Open in Play Store',
    subtitle: 'View Android application installation listing',
    icon: 'url',
    category: 'PRIMARY',
    isPrimary: true,
    accessibilityHint: 'Opens Google Play Store application page.',
  },
  OPEN_APP_STORE: {
    id: 'OPEN_APP_STORE',
    label: 'Open in App Store',
    subtitle: 'View Apple iOS store application listing',
    icon: 'url',
    category: 'PRIMARY',
    isPrimary: true,
    accessibilityHint: 'Opens Apple App Store listing page.',
  },
  OPEN_WHATSAPP: {
    id: 'OPEN_WHATSAPP',
    label: 'Open WhatsApp',
    subtitle: 'Launch chat interface with recipient number',
    icon: 'whatsapp',
    category: 'PRIMARY',
    isPrimary: true,
    accessibilityHint: 'Opens WhatsApp conversation with the encoded phone number.',
  },
  OPEN_YOUTUBE: {
    id: 'OPEN_YOUTUBE',
    label: 'Watch on YouTube',
    subtitle: 'Open streaming media player for video or channel',
    icon: 'url',
    category: 'PRIMARY',
    isPrimary: true,
    accessibilityHint: 'Launches YouTube video streaming player.',
  },
  OPEN_FACEBOOK: {
    id: 'OPEN_FACEBOOK',
    label: 'Open Facebook Profile',
    subtitle: 'View social network page or individual profile',
    icon: 'url',
    category: 'PRIMARY',
    isPrimary: true,
    accessibilityHint: 'Opens Facebook social media application.',
  },
  OPEN_INSTAGRAM: {
    id: 'OPEN_INSTAGRAM',
    label: 'Open Instagram',
    subtitle: 'View Instagram handle profile or post',
    icon: 'url',
    category: 'PRIMARY',
    isPrimary: true,
    accessibilityHint: 'Opens Instagram social media page.',
  },
  OPEN_LINKEDIN: {
    id: 'OPEN_LINKEDIN',
    label: 'Open LinkedIn Profile',
    subtitle: 'View professional network resume and portfolio',
    icon: 'url',
    category: 'PRIMARY',
    isPrimary: true,
    accessibilityHint: 'Opens LinkedIn professional profile in app or browser.',
  },
  OPEN_UPI_PAYMENT: {
    id: 'OPEN_UPI_PAYMENT',
    label: 'Pay via UPI App',
    subtitle: 'Launch GPay, PhonePe, or Paytm with payee details',
    icon: 'externalLink',
    category: 'PRIMARY',
    isPrimary: true,
    accessibilityHint: 'Opens installed UPI financial applications to complete instant payment.',
  },
  CONNECT_WIFI: {
    id: 'CONNECT_WIFI',
    label: 'Connect to Wi-Fi',
    subtitle: 'Attempt direct network connection or copy parameters',
    icon: 'wifi',
    category: 'PRIMARY',
    isPrimary: true,
    requiresConfirmation: true,
    confirmationPrompt: {
      title: 'Connect to Wi-Fi Network',
      message: 'Do you want to attempt connection to this wireless network access point?',
      confirmLabel: 'Connect Network',
      cancelLabel: 'Cancel',
    },
    accessibilityHint: 'Requests system permission to connect to this Wi-Fi network.',
  },
  CREATE_CONTACT: {
    id: 'CREATE_CONTACT',
    label: 'Add to Contacts',
    subtitle: 'Save vCard profile to device address book',
    icon: 'contact',
    category: 'PRIMARY',
    isPrimary: true,
    accessibilityHint: 'Imports contact details directly into your phone address book.',
  },
  CREATE_CALENDAR: {
    id: 'CREATE_CALENDAR',
    label: 'Add to Calendar',
    subtitle: 'Schedule event dates and alert reminders in calendar',
    icon: 'calendar',
    category: 'PRIMARY',
    isPrimary: true,
    accessibilityHint: 'Adds event schedule into your device calendar application.',
  },
  COPY_WIFI_PASSWORD: {
    id: 'COPY_WIFI_PASSWORD',
    label: 'Copy Password',
    subtitle: 'Copy only Wi-Fi network security passphrase',
    icon: 'copy',
    category: 'QUICK',
    accessibilityHint: 'Copies the extracted Wi-Fi password to clipboard.',
  },
  COPY_UPI_ID: {
    id: 'COPY_UPI_ID',
    label: 'Copy UPI VPA ID',
    subtitle: 'Copy only merchant or payee UPI VPA identifier',
    icon: 'copy',
    category: 'QUICK',
    accessibilityHint: 'Copies the extracted UPI financial payment ID to clipboard.',
  },
  COPY_COORDINATES: {
    id: 'COPY_COORDINATES',
    label: 'Copy GPS Coords',
    subtitle: 'Copy exact latitude and longitude numerical block',
    icon: 'copy',
    category: 'QUICK',
    accessibilityHint: 'Copies geographical GPS latitude and longitude numbers.',
  },
  OPEN_BARCODE_SEARCH: {
    id: 'OPEN_BARCODE_SEARCH',
    label: 'Search Product Online',
    subtitle: 'Look up barcode item pricing and reviews on Google',
    icon: 'barcode',
    category: 'PRIMARY',
    isPrimary: true,
    accessibilityHint: 'Runs an internet product query for this scanned retail barcode number.',
  },
  GENERATE_QR_FROM_RESULT: {
    id: 'GENERATE_QR_FROM_RESULT',
    label: 'Generate Custom QR',
    subtitle: 'Encode this payload into a stylized matrix image',
    icon: 'generator',
    category: 'SECONDARY',
    accessibilityHint: 'Transfers this decoded string into the QR Matrix Studio for customization.',
  },
  TOGGLE_FAVORITE: {
    id: 'TOGGLE_FAVORITE',
    label: 'Favorite',
    subtitle: 'Add or remove item from saved bookmarks vault',
    icon: 'favorite',
    category: 'QUICK',
    requiresConfirmation: true, // will conditionally trigger prompt only when removing from favorites!
    confirmationPrompt: {
      title: 'Remove from Favorites',
      message: 'Are you sure you want to un-favorite this saved record?',
      confirmLabel: 'Remove',
      cancelLabel: 'Keep Starred',
      isDestructive: true,
    },
    accessibilityHint: 'Toggles favorite star status for this captured record.',
  },
  DELETE_HISTORY_ITEM: {
    id: 'DELETE_HISTORY_ITEM',
    label: 'Delete Scan Record',
    subtitle: 'Permanently wipe entry from local database vault',
    icon: 'delete',
    category: 'SECONDARY',
    isDestructive: true,
    requiresConfirmation: true,
    confirmationPrompt: {
      title: 'Delete Scan Record',
      message: 'Are you sure you want to permanently remove this scanned item from memory?',
      confirmLabel: 'Delete Record',
      cancelLabel: 'Cancel',
      isDestructive: true,
    },
    accessibilityHint: 'Deletes this scan from your permanent local storage history.',
  },
  RENAME_HISTORY_ITEM: {
    id: 'RENAME_HISTORY_ITEM',
    label: 'Rename Scan Record',
    subtitle: 'Assign a personalized display title or tag label',
    icon: 'edit',
    category: 'SECONDARY',
    accessibilityHint: 'Opens an editor dialogue to give a custom name to this scanned code.',
  },
  CLEAR_HISTORY_ITEM: {
    id: 'CLEAR_HISTORY_ITEM',
    label: 'Clear History Buffer',
    subtitle: 'Purge current record cache from active discovery view',
    icon: 'delete',
    category: 'SECONDARY',
    isDestructive: true,
    requiresConfirmation: true,
    confirmationPrompt: {
      title: 'Clear History Item',
      message: 'Do you want to clear this item from your historical discovery buffer?',
      confirmLabel: 'Clear Item',
      cancelLabel: 'Keep Active',
      isDestructive: true,
    },
    accessibilityHint: 'Clears the current record from the display buffer.',
  },
};
