import { ComponentProps } from 'react';
import { MaterialCommunityIcons } from '@expo/vector-icons';

export type IconName = ComponentProps<typeof MaterialCommunityIcons>['name'];

export const icons: Record<string, IconName> = {
  qr: 'qrcode-scan',
  barcode: 'barcode-scan',
  camera: 'camera',
  flashlight: 'flashlight',
  flashlightOff: 'flashlight-off',
  history: 'history',
  settings: 'cog-outline',
  generator: 'qrcode-edit',
  close: 'close',
  check: 'check',
  search: 'magnify',
  arrowBack: 'arrow-left',
  chevronRight: 'chevron-right',
  chevronDown: 'chevron-down',
  share: 'share-variant',
  copy: 'content-copy',
  delete: 'trash-can-outline',
  info: 'information-outline',
  warning: 'alert-outline',
  error: 'alert-circle-outline',
  success: 'check-circle-outline',
  more: 'dots-vertical',
  filter: 'filter-variant',
  refresh: 'refresh',
  externalLink: 'open-in-new',
  star: 'star-outline',
  starFilled: 'star',
  home: 'home-variant-outline',
  user: 'account-outline',
  tag: 'tag-outline',
  // New Phase 2 Icons
  gallery: 'image-multiple-outline',
  favorite: 'heart-outline',
  favoriteFilled: 'heart',
  privacy: 'shield-lock-outline',
  shieldCheck: 'shield-check-outline',
  help: 'help-circle-outline',
  rate: 'star-box-outline',
  chart: 'chart-bar',
  wifi: 'wifi',
  contact: 'account-box-outline',
  phone: 'phone-outline',
  email: 'email-outline',
  sms: 'message-text-outline',
  location: 'map-marker-outline',
  calendar: 'calendar-month-outline',
  text: 'text-box-outline',
  url: 'link-variant',
  folder: 'folder-outline',
  palette: 'palette-outline',
  language: 'translate',
  colorPalette: 'palette',
  // Phase 3 Home Screen Icons
  bell: 'bell-outline',
  arrowRight: 'arrow-right',
  clock: 'clock-outline',
  lightbulb: 'lightbulb-on-outline',
  sparkles: 'creation',
  offline: 'wifi-off',
  fast: 'lightning-bolt-outline',
  secure: 'lock-check-outline',
  copyright: 'copyright',
  // Phase 4 Scanner Icons
  myQr: 'qrcode',
  target: 'target',
  viewfinder: 'crosshairs-gps',
  scanHelper: 'scan-helper',
  // Phase 5 Scan Result Icons
  report: 'flag-outline',
  rename: 'pencil-outline',
  export: 'export-variant',
  save: 'content-save-outline',
  learn: 'book-open-variant-outline',
  empty: 'folder-open-outline',
  // Phase 6 Generator Icons
  whatsapp: 'whatsapp',
  instagram: 'instagram',
  facebook: 'facebook',
  youtube: 'youtube',
  linkedin: 'linkedin',
  duplicate: 'content-duplicate',
  reset: 'backup-restore',
  download: 'tray-arrow-down',
  shape: 'shape-outline',
  image: 'image-outline',
  slider: 'tune-vertical',
  template: 'cards-outline',
  // Phase 8 Favorites Icons
  list: 'format-list-bulleted',
  grid: 'view-grid-outline',
  checkbox: 'checkbox-marked',
  checkboxOutline: 'checkbox-blank-outline',
  sort: 'sort-variant',
  // Phase 9 Settings & Sub-screens Icons
  backup: 'cloud-upload-outline',
  restore: 'cloud-download-outline',
  import: 'file-import-outline',
  bug: 'bug-outline',
  faq: 'frequently-asked-questions',
  developer: 'code-tags',
  license: 'certificate-outline',
  vibrate: 'vibrate',
  sound: 'volume-high',
  animation: 'animation-outline',
  compact: 'view-compact-outline',
  appInfo: 'cellphone-information',
  react: 'react',
  github: 'github',
  twitter: 'twitter',
  reddit: 'reddit',
  discord: 'forum',
  // Phase 16 QR Generator Studio Icons
  playstore: 'google-play',
  appstore: 'apple',
  wallet: 'wallet-outline',
  bitcoin: 'bitcoin',
  cash: 'cash-multiple',
  store: 'store-outline',
};
